name: "Sample react ci pipeline/workflow"

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "setup nodejs environment"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "check version"
        run: node --version
