name: "Schedule pipeline"

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: simple step
        run: echo "Hello world"
