name: "Schedule pipeline"

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes (more reliable)
  workflow_dispatch:         # lets you also run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: simple step
        run: echo "Hello world"
